book/makefile
the makefile has three targets
* all, which does the complete build
* fast, which only runs pdflatex once
* clean, that removes files generated by the makefile
=> A makefile

makefile
The README says `make release` should build the ebooks, but it's building the PDF (same command as in `make build_book`). Maybe this should run `make release` inside the books folder?
=> Fix relase rule in main makefile

book/flour-types/flour-types.tex, book/sourdough-starter/sourdough-starter-types.tex
Cleaned up phrasing, added commas as needed
I did not change whether grams was spelled out or abbreviated; I only fixed where it said 50g rather than 50 g
Americans call it whole grain flour; Brits call it whole meal flour, but neither usually says "whole flour"
(You can think of this as the beginnings of my personal, doc-specific style guide)
* Dependent clauses of more than 5 words that begin a sentence (e.g., "_Because_ I went to the store", "_Since_ he had to leave early", "_If_ you are making a lot of bread", "_When_ he found the body") need a comma before the main part of the sentence.  Phrases with fewer words may still want a comma to be more readable.
* When units are abbreviated, there still needs to be a space in between the numeral and the unit (e.g., 50 g)
* Add subscript for …
=> Minor punctuation, grammatical fixes to Starter Types and Flour Types

README.md, book/figures/export_figures.sh, book/makefile
This adds a `make export_figures` command which exports all the flow charts into nicely looking pngs. The command requires that you have docker running locally.
Example:
=> Export figures feature

makefile
When a user is not a member of the `docker` group they need to run the build with sudo - `sudo make`.
This fails however as `$(PWD)` resolves to nothing and you get the following error
```
Successfully tagged the-sourdough-framework:latest
docker run -it -v WD:/opt/repo the-sourdough-framework /bin/bash -c "cd /opt/repo/book && make build_pdf"
/bin/bash: line 1: cd: /opt/repo/book: No such file or directory
make: *** [makefile:3: build_book] Error 1
```
Replacing `$(PWD)` with `.` means the same thing but allows the builds to be run with sudo
=> Fix no such file error when running docker via sudo

.gitignore, README.md, book/book.tex, book/makefile
This adds another build process where the book is built using a sans serif font. This can facilitate reading the book for some users. This fixes #85
=> Accessibility Sans Serif Option

.gitignore, book/book-ebook.css, book/book.mk4, book/makefile, book/tex4ebook.cfg
Removes fixed height and width from the resulting HTML and adds an additional css for the ebook formats. This is related to #59. It doesn't fix the apple books though.
=> Ebook improvements

book/sourdough-starter/sourdough-starter.tex
Fixed a 'typo' or rather a weird sentence. 
"[...] less or more, **and just and** eyeball [...]" -> "[...] less or more, **or just** eyeball [...]" 
Maybe you forgot something to write there although I don't know what.. In the branch "improve-troubleshoothing-wording" this sentence has already been rewritten, but I don't know which branch you'll be using in the end. 
I just wanted to make you aware of this :)
=> Fixed 'typo' in sourdough-starter.tex

.gitignore, book/makefile
This fixes the `make export_figures` command. See discussion in #119
=> Fix export figures

.github/workflows/validate.yml
They are not needed as you can change the font in your reader. Closes: https://github.com/hendricius/the-sourdough-framework/issues/131
=> Remove building sans-serif ebook in CI

book/sourdough.sty
Main change will be the use of OpenSans for the sans serif book, among with units not written in math font (as Open Sans does not have a math font)
The rest is colors definition.
=> Align to hardcover book

book/wheat-sourdough/wheat-sourdough.tex
For some reason I used dough mass. It should be flour mass. This uses baker's math properly. Fixes #164
=> Fix dough mass. Should be flour mass.

book/figures/fig-bulk-fermentation.tex
This fixes a flowchart having text overlapping elements inside of the chart.
**Before:**
**After:**
=> Fix flowchart overflow

book/baking/baking.tex, book/book.tex, book/bread-types/bread-types.tex, book/cover/cover.tex, book/makefile, book/non-wheat-sourdough/non-wheat-sourdough.tex, book/sourdough-starter/sourdough-starter.tex, book/sourdough.sty, book/troubleshooting/misc.tex, book/website.cfg, book/wheat-sourdough/wheat-sourdough.tex, website/modify_build.rb
So we can more easily access those flowcharts from pdf and website, rather than looking in the crowded list of figures.
=> Add a flowchart environnement and its listof

book/sourdough.sty
Metadata added to the pdf, readable with pdfinfo
Title:           The Sourdough Framework
Subject:         The sourdough bread baking bible
Keywords:        Sourdough, dough, bread, wheat, baking, bake,
home-baking, yeast, rye, crumb, debug, gluten, dough strength, crust,
DIY, framework, https://the-sourdough-framework.com,
https://www.the-bread-code.io/,
https://github.com/hendricius/the-sourdough-framework, open-source,
CC-BY-SA
Author:          Hendrik Kleinwächter
Creator:         LaTeX with hyperref
Producer:        LuaTeX-1.16.0
CreationDate:    Sun Aug 27 13:58:19 2023 BST
ModDate:         Sun Aug 27 13:58:19 2023 BST
Custom Metadata: yes
Metadata Stream: no
Tagged:          no
UserProperties:  no
Suspects:        no
Form:            none
JavaScript:      no
Pages:           167 …
=> Add pdinfo metadata

book/style.css, website/assets/script.js
This uses vanilla JavaScript to cycle through section headings and add a unicode chain 🔗 link for permalinks to take one directly to it. Mostly this is useful when someone has already been scrolling pretty far and they find what they're looking for and want a link straight to it without scrolling back to the ToC to find it again.
See "Baker's Math" heading in this screenshot:
=> Permalinks for website section heads

website/assets/script.js, website/modify_build.rb
Moves the generation of the hyperlink indicator to the html directly. Followup to #272.
FYI @sha1sum
=> Create anchors in website generator

book/makefile
Solves https://github.com/hendricius/the-sourdough-framework/issues/273 by removing dvisvgm_hashes
Not sure why you had this option to start with ?  Will there be regressions to remove it?
=> Fix giberrish website timeline

Dockerfile, makefile, website/modify_build.rb
FYI @cedounet 
```
uname -a
Linux d887876c6f8d 6.3.13-linuxkit #1 SMP PREEMPT Thu Sep  7 07:48:47 UTC 2023 x86_64 GNU/Linux
/bin/bash --version
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
latexmk --version
Latexmk, John Collins, 4 Apr. 2023. Version 4.80
lualatex --version
This is LuaHBTeX, Version 1.17.0 (TeX Live 2023)
Development id: 7581
Execute  'luahbtex --credits'  for credits and version details.
There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or …
```
=> Use trixie as base image

.github/workflows/validate-book-build.yml
Rational is as follow:
- We ran validate-book on each push on the PR branch anyway
- We will run release_book which is a superset of validate
=> Prevent running validate when pushing on main

.github/workflows/validate-book-build.yml, makefile
This will store the built book on every pull request and attach it to the workflow:
This way we can always see the preview of what we are about to merge before actually merging. Downside - it adds a bit of build time to upload everything.
=> Upload artifacts on each PR

book/sourdough.sty
Apparently it breaks on kobo e-reader, see https://github.com/hendricius/the-sourdough-framework/issues/306
=> Prevent tex4ht to load enumitem

.github/workflows/docker-build-push.yml, Dockerfile, makefile
Builds the Docker image in both `arm64` and `amd64` architectures, which will add the ability for Mac M1/M2/M3 users to run the container without emulation.
Fixes #308
=> #308 — Build docker image for both amd64 and arm64

.github/workflows/docker-build-push.yml, Dockerfile, makefile
This reverts commit e6709b0f5e363b526b3698c8de05effbfb22f3ea.
https://github.com/actions/runner-images/issues/5631
It seems like there is no proper arm64 support yet. So we need to live with the slightly lower image for MacOS now 😎 .
FYI @sha1sum
=> Revert "#308 — Build docker image for both amd64 and arm64 (#311)"

.gitignore, makefile
- Adds `.DS_Store` to `.gitignore` for Mac users.
- Adds `--rm` option flag to `docker` command so that containers are removed when the process is finished rather than leaving a bunch of containers around.
=> Small changes to Docker command and `.gitignore`

book/glossary/glossary.tex, book/troubleshooting/misc.tex
The float test is not super reliable - this adds some comments on when it can work and when it does not.
=> Add note on float test

book/book.tex, book/intro/foreword.tex
It's empty and does not provide any value unless we actually manage to have a decent foreword. So this removes it for now.
=> Remove foreword

book/style.css, website/modify_build.rb
Good job spotting this. This fixes #345.
They are also centered now in the white container.
=> Fix flowchart border on website

book/figures/fig-starter-readiness.tex
First flow chart is about creating a starter - the other one about maintenance. The suggested approach is slightly different. This makes it clear that one flow chart is about creating a starter.
Fix #351
=> Fix confusing flow chart

.github/workflows/release-book-website.yml, makefile
This temporarily removes the parallel option from make to ensure that we can release the booklet. I am not sure why it causes an issue. Baking the book without it causes no problem.
I also recommend that we use the `bake` option for the testing workflow in the future. This increases build time but makes sure we don't merge something that might now work.
=> Remove parallel option from make

book/wheat-sourdough/wheat-sourdough.tex
Tidied up some duplication in the section on aliquot where similar statements were made in the same paragraph.
> The sample is extracted after creating the initial dough strength.
> The aliquot sample is extracted after creating dough strength.
=> Remove redundant aliquot statement

book/sourdough.sty
This was prevented by ocgcolorlinks which was here to have links printed in black but looking like colors in the pdf on screen... as Doc hyperref explains:
• Main disadvantage: Links cannot be broken across lines. PDF reference
1.7: 4.10.2 “Making
=> Allow URL to break

.gitignore, book/makefile
A simple change to create a reduced size color epub for readers that have color but a size limit. The resulting file is ~30MB
=> epub_reduced size

.gitignore, book/makefile
@cedounet This is the first two parts of the discussion on the [issue with keeping the epub size below 50 MB](https://github.com/hendricius/the-sourdough-framework/issues/401#issuecomment-2565432172) 
A few points that I am struggling with:
- when I do a `make mrproper`, I have to `make bake` twice in order to complete the build. I'm not sure if my changes are causing this issue or not. 
- I was trying to determine a way to go directly to the condensed images, but I am unsure of a way to do that (maybe the current way is best).
- `epub_build` folder does not appear to be in .gitignore. I was not sure if there was a reason for this. 
- I can check the file size (using something simple like `$(du -sb $filename | cut -f1)`, but should the test error out on > 50MB?
=> epub - change to lower res file

book/figures/fig-starter-process.tex, book/figures/fig-stiff-starter-conversion.tex, book/figures/flowcharts_tikz.tex
- Change tikzstyle definition for "line" so that all flowchart arrows have the "Latex" styling.
- Fix the little line that the above change introduces in fig-stiff-starter-conversion.tex
- Change fig-starter-process.tex to use the global "line" style; accept the proposed sidebar syntax.
=> Update all flowchart arrows to "Latex" arrows

book/figures/fig-starter-process.tex, book/figures/flowcharts_tikz.tex
- Use maingray from colors.tex instead of hardcoded value.
- Remove font size specification in side bar.
- Use \eg to generate e.g. in standard way
- Update flowcharts_tikz.tex to use arrows.meta instead of arrows, rather than in addition to.
=> Bring previous commits in line with standards.

book/wheat-sourdough/wheat-sourdough.tex
Hi,
in the the "dough strength" section of the wheat sourdough chapter, the section on machine kneading suggests using the same technique as "figure 7.3".
Figure 7.3 does not seem relevant here; there is, however, a _flowchart_ 7.3, which I believe was the intended reference?
=> Correct reference to flowchart in dough strength section

book/figures/fig-liquid-starter-conversion.tex, book/figures/fig-stiff-starter-conversion.tex, book/plots/fig-temperature-ambient.tex, book/plots/fig-temperature-surface.tex, book/plots/fig-yeast-sourdough-strength.tex
- the arrows in the "repeat 3 times" elements in starter conversion figures.
- the arrows used for x/y axes in the three plots that are generated
=> Update more arrows to match the flow arrows in flowcharts.

book/sourdough.sty, book/style.css, book/tex4ebook.cfg, book/website.cfg
@hendricius, second attempt... way less intrusive.
Please review.  
C
=> Sans serif pics website 2

book/sourdough-starter/sourdough-starter.tex
- Move flow chart to top of Making a Starter Section
- Move Microbe War figure to paragraph after "epic battle"
=> Improve float placement in Starter section

README.md
This PR swaps the links for TL;DR versions in README.md, in order to match the text.
=> fix: Swap links of TL;DR versions in README.md

book/sourdough-starter/sourdough-starter-types.tex, book/wheat-sourdough/wheat-sourdough.tex
Fixes bug 444
https://github.com/hendricius/the-sourdough-framework/issues/444
Reformat paragraphs to 80 colmuns while at it.
=> Fix capitalization issues

book/sourdough.sty
flowchart/table/figures
I ma not sure why we reduced the figures caption font size in the first place?
tree 4b38c6977ac522207d7b5c5615211b98879cefdc
parent 904519db473a86c5f6da66d29a7a16af5ebe6851
author Hendrik Kleinwaechter Fri Dec 30 13:36:14 2022 +0100
Document index page, reduce size of footnotes
Shall we reduce them all or all in normal size?
What do you think?
=> Same size for all captions

book/wheat-sourdough/wheat-sourdough.tex
It's more grammatical in English to replace "So" with "Neither" here.
WARNING: POSSIBLY BORING LANGUAGE REASON AHEAD:
The best way I can think to explain it is that because "so" is a coordinating conjunction here; it's indicating that if P happens, Q will also happen:
```
"If your aliquot sample rises, so will your main dough"
means
P -> Q
```
In this sentence, however, clause P isn't about something happening; It's about something _not_ happening (the dough not having a good balance), it's about `!P -> !Q`
In this case, it's more grammatical to use the negative conjunction "neither".
(Annoying additional English quirk; If you were making definitive statements, neither stops being coordinating!
```
"You don't have a job; neither does your friend" 
means 
!P & !Q
```
But if you add back in …
=> Correct conjuctive/conditional agreement.

book/makefile
1) ebook was still using the old target
2) Do not call mkdir -p for every single image conversion
=> Fix epub build and remove redudant mkdir calls

book/makefile
- Add the tex4ht workaround
- define src_recipe before adding it to src_tex
- have vars.tex as dependencies for figures even if we use it only for standalone
=> Fix dependencies in makefile
