- book/history/sourdough-history.tex
woo first PR by a random contributor
> Tidy up history chapter

- book/intro/preface.tex
Hi Hendrik, I'm not sure if these kinds of changes are welcome, but I love what you're doing and wanted to contribute in some way to your book. I've gone through your preface and made grammatical edits (insertion of commas, capitalization of proper nouns, etc.) and have also made modest changes to style where I felt (subjectively) that it made the text flow better for the reader.
If these kinds of edits are welcome, I'd love to do the same for other chapters in your book as well. Thank you so much for working on this valuable resource!
> Grammar and style edits to the preface

- book/basics/how-sourdough-works.tex
Hi Hendrik,
I've just finished (mostly) editing the bacteria section of the "How Sourdough Works" chapter. I did have one question for you about my edits, which I left as a latex comment in the code. Please take a look and let me know how you'd like me to address that last paragraph. I've finished the rest of the section.
> Bacteria section

- book/book.tex
- book/sourdough-starter/sourdough-starter.tex
Recreating the sourdough flowchart in tikz.
> Sourdough start tikz flowchart

- book/book.tex
- book/sourdough-starter/sourdough-starter.tex
Also updates the chart style to match the bread code colors
> Fix small mistaske

- book/basics/how-sourdough-works.tex
- book/sourdough-starter/sourdough-starter.tex
Mostly just typo fixes.  There are a few changes to singular/plurals in section 2.2 (Yeast) to read more naturally to me.  
There are also a few changes to phrasing and the occasional addition of commas.
Feel free to use or ignore the changes as you prefer.
> Typo fixes

- .github/workflows/main.yml
Gluten Tag, I really enjoy your content and have been able to improve my bread and pizza making skills a lot because of it. Thanks for sharing, Henrik. 
I just wanted to give something back in the form of this PR solving #28 by creating a release workflow in Github. I created one myself in my fork, check there if that meets your requirements to solve this problem, i.e. offer the built PDF in Github via releases?
 ✌️ Andreas
> Add release workflow with LaTeX builds

- .github/workflows/main.yml
- .github/workflows/validate.yml
- book/makefile
This will automatically release the book to S3 after merging pull requests.
Big shoutout to @ndrsfel - thanks a lot for the support!
> Build and release book to AWS S3 on merge to main

- book/wheat-sourdough/wheat-sourdough.tex
> Fix typo in Wheat Sourdough chapter

- book/book.tex
- book/references.bib
- book/storing-bread/storing-bread.tex
This adds the chapter that looks at different bread storing options.
IMHO it would be nice to also add some pictures. I didn't have time to add them yet.
> Storing Bread Chapter

- README.md
- book/intro/acknowledgements.tex
I can't believe it. After almost a year we finally have a decent book. I am happy to remove the [WIP] flag for now.
Edit: Thanks everyone who helped so far here on GitHub. I highly appreciate it!
> Remove WIP Flag

- book/baking/baking.tex
I added periods on the end of the numbered list lines to maintain consistency since there were some larger punctuated blocks of text already.  Otherwise just a few changes for style/clarity.
As always feel free to use them or not as you'd like.
> Typo fixes for baking chapter

- book/troubleshooting/misc.tex
- book/wheat-sourdough/wheat-sourdough.tex
This updates the FAQ adding a note on autolysis.
> FAQ: Should I autolyse

- book/sourdough-starter/sourdough-starter.tex
- book/troubleshooting/misc.tex
This adds some troubleshooting for people having issues with making a starter.
> FAQ: Starter not rising

- book/sourdough-starter/sourdough-starter-types.tex
Based on the feedback by @gszabo this improves the paragraph with more information.
> Clarify low inoculation

- book/troubleshooting/misc.tex
- book/wheat-sourdough/wheat-sourdough.tex
This adds more frequently asked questions and possible troubleshooting.
> Add more FAQ Items

- book/basics/how-sourdough-works.tex
- book/makefile
Small improvements. Generally speaking this is my favorite chapter. It shows nicely why yeasts/bacteria live in the wild and the role they have.
> Improvements grammar/spelling sourdough works

- book/baking/baking.tex
- book/book.tex
- book/bread-types/bread-types.tex
- book/history/sourdough-history.tex
- book/sourdough-starter/sourdough-starter-types.tex
- book/sourdough-starter/sourdough-starter.tex
- book/troubleshooting/crumb-structures/crumb-structures.tex
- book/troubleshooting/misc.tex
- book/wheat-sourdough/wheat-sourdough.tex
This uses the chemformula package to improve the display of chemical formulas.
FYI @joseabernardes and @hanclintonnyx. Thanks for the idea!
> Fix chemical formula display

- book/flour-types/flour-types.tex
- book/references.bib
- book/tables/table-flour-types.tex
This improves the flour types section with some feedback from Adam Carter (sent via email). Thank you ❤️
> Add feedback on flour types

- book/bread-types/bread-types.tex
- book/tables/table-overview-bread-types.tex
This adds additional feedback by Adam Carter on the the bread types chapter. Thank you ❤️
> Bread types feedback

- book/basics/how-sourdough-works.tex
- book/history/sourdough-history.tex
- book/references.bib
- book/sourdough-starter/sourdough-starter-types.tex
- book/troubleshooting/misc.tex
This adds more sources to some places where I didn't add them before.
> Add sources

- book/figures/fig-bulk-fermentation.tex
- book/wheat-sourdough/wheat-sourdough.tex
This adds a flow chart showing how to determine when the bulk fermentation is completed.
> Bulk fermentation complete flowchart

- book/baking/baking.tex
- book/bread-types/bread-types.tex
- book/non-wheat-sourdough/non-wheat-sourdough.tex
- book/storing-bread/storing-bread.tex
- book/troubleshooting/crumb-structures/crumb-structures.tex
- book/troubleshooting/misc.tex
- book/wheat-sourdough/wheat-sourdough.tex
Proofreading Notes:
- freestanding: one word
- flatbread: breads such as pita, naan, etc., that are not meant to rise much vs. flat bread: bread which unintentionally came out flat
- Maillard is capitalized (named for Louis-Camille Maillard)
- My statement in a previous comment was mistaken regarding the five-word rule for introductory phrases and clauses.  It's [four words](https://www.grammarly.com/blog/commas-after-introductory-phrases/).
> Proofreading for rest of the book text.

- book/troubleshooting/misc.tex
Additional suggestions for dealing with chlorinated water.
> Suggested text re: chlorinated water.

- book/bread-types/bread-types.tex
- book/intro/preface.tex
- book/sourdough-starter/sourdough-starter-types.tex
- book/troubleshooting/crumb-structures/crumb-structures.tex
- book/troubleshooting/misc.tex
- book/wheat-sourdough/wheat-sourdough.tex
Added corrections made in red as per the pdf linked in discord. Some corrections have already been made.
> Grammatical corrections as per google drive.

- book/troubleshooting/misc.tex
This adds a section looking at the topic of what's the best starter feeding ratio.
> What's the best starter feeding ratio?

- book/wheat-sourdough/wheat-sourdough.tex
Found via `typos --format brief`
> Fix typo, strucuture -> structure

- book/sourdough-starter/sourdough-starter.tex
This crucial paragraph on starting your starter was quite dense with information so just refactoring it a bit to improve how it parses. Absolutely no offence taken if you do not want to change it, but I tried my bets to maintain your style/voice.
> docs: :art: restructure making first starter instructions

- .github/workflows/main.yml
- .github/workflows/validate.yml
- README.md
- book/makefile
- makefile
I feel like since this is bread related, release should be renamed to "bake". So `make bake` will bake you all the different book versions.
> 🤡 Add "make bake" command

- book/sourdough-starter/sourdough-starter-types.tex
> Fix typo in sourdough-starter-types.tex

- book/baking/baking.tex
- book/book.tex
- book/bread-types/bread-types.tex
- book/flour-types/flour-types.tex
- book/makefile
- book/sourdough-starter/sourdough-starter-types.tex
- book/sourdough-starter/sourdough-starter.tex
- book/storing-bread/storing-bread.tex
- book/tables/table-bakers-math-example.tex
- book/tables/table-baking-process-stages.tex
- book/tables/table-dough-size-increase.tex
- book/tables/table-fermentation-effects.tex
- book/tables/table-flat-bread-pancake-recipe.tex
- book/tables/table-flour-types.tex
- book/tables/table-grains-bread-making-process.tex
- book/tables/table-oven-baking-overview.tex
- book/tables/table-overview-bread-types.tex
- book/tables/table-overview-w-values.tex
- book/tables/table-ph-values-dough.tex
- book/tables/table-recipe-bakers-math.tex
- book/tables/table-starter-types.tex
- book/tables/table-starter-usage-activity.tex
- book/tables/table-storing-bread-overview.tex
- book/tables/vars.tex
- book/wheat-sourdough/wheat-sourdough.tex
2nd Try...
let's see how it goes on your side, maybe I am lucky and it fixes both problems.
> Nicer tables episode II

- book/baking/baking.tex
- book/basics/how-sourdough-works.tex
- book/book.tex
- book/bread-types/bread-types.tex
- book/figures/fig-baking-process.tex
- book/figures/fig-liquid-starter-conversion.tex
- book/figures/fig-starter-maintenance.tex
- book/figures/fig-stiff-starter-conversion.tex
- book/figures/fig-wheat-sourdough-starter-process.tex
- book/flour-types/flour-types.tex
- book/history/sourdough-history.tex
- book/intro/acknowledgements.tex
- book/intro/preface.tex
- book/makefile
- book/non-wheat-sourdough/non-wheat-sourdough.tex
- book/sourdough-starter/sourdough-starter-types.tex
- book/sourdough-starter/sourdough-starter.tex
- book/storing-bread/storing-bread.tex
- book/troubleshooting/crumb-structures/crumb-structures.tex
- book/troubleshooting/misc.tex
- book/wheat-sourdough/wheat-sourdough.tex
This PR is mainly the result of running static checkers on LaTeX source and fixing the ones I undersand/agree with.
- a new target to run checkers lacheck and chktex
- fix errors, note this war mostly automated then verified quickly by visual inspection
- fix a few others I saw while inspecting
- use emph instead of italic, and for quoted words..
Should not make any huge changes to the document, more helping TeX to take the right decision
> Improve typography

- book/makefile
Saving polar bears one makefile at a time...
1) Saves 5 minutes on github actions build time and on my machine
2) some more generic rules in the makefile
3) Looks OK in calibre as well
Please have a look and let me know
> Ebooks build

- book/troubleshooting/crumb-structures/crumb-structures.tex
and traling spaces while at it
> Remove superflous equal sign

- book/basics/how-sourdough-works.tex
- book/references.bib
This just adds a small note on temperature when milling flour. The provided source is an interesting read.
> Add note on temperature and milling flour

- book/basics/how-sourdough-works.tex
cite not ref, unbreakable space and grammar.
> Fix reference and grammar

- book/basics/how-sourdough-works.tex
- book/book.tex
- book/history/sourdough-history.tex
- book/intro/acknowledgements.tex
- book/makefile
- book/supporters.csv
- book/troubleshooting/crumb-structures/crumb-structures.tex
- Remove Obsolete packages
- Change supporters display
- Removed warnings at compilation time
> Various clean up

- .github/workflows/main.yml
- .gitignore
- README.md
- book/makefile
This is a minimal alpha version of the book as static html website. More stuff needs to be added, but should be okay for a working prototype. Fixes #128
> Static HTML Website (alpha version)

- .gitignore
- book/book.mk4
- book/book.tex
- book/makefile
- book/style.css
- book/website.cfg
Big thanks to @michal-h21 for the improvements.
> Website improvements for book

- book/book.tex
fixes https://github.com/hendricius/the-sourdough-framework/issues/142
> Fix links colors

- book/makefile
- website/modify_build.rb
This fixes the default auto generated LaTeX titles for the website
> Fix titles

- book/history/sourdough-history.tex
Small typo. Thanks for the book!
> Fix typo: "The future of human [b]read"

- book/bread-types/bread-types.tex
- book/flour-types/flour-types.tex
- book/intro/preface.tex
- book/sourdough-starter/sourdough-starter.tex
- book/tables/table-flat-bread-pancake-recipe.tex
- book/tables/table-starter-usage-activity.tex
- book/troubleshooting/crumb-structures.tex
- book/troubleshooting/misc.tex
- book/wheat-sourdough/wheat-sourdough.tex
a pot-pourri of tiny changes and fixes.
> Small fixes

- book/makefile
Typo in clean rule, should fix website generation
> Fix clean rule

- book/makefile
- website/makefile
- Declare your dependencies
- Do not rebuild unless dependencies changed
- Cleanup after yourself
- Document your targets
- COMMANDS in upper case and variables/rules in lowercase
> Use standard practices for website build

- .github/workflows/release-website.yml
- makefile
- website/README.md
This improves the documentation on how to build the website and applies a couple of additional fixes. Followup to #161
> Improve website build documentation

- website/assets/robots.txt
- website/modify_build.rb
This creates a sitemap for the website for improved SE indexing.
> Create website sitemap

- book/book.tex
- book/intro/preface.tex
Make pragraph indentation as per Hendrik's liking.
> Remove first-line indentation

- book/figures/fig-baking-process.tex
- book/figures/fig-bulk-fermentation.tex
- book/figures/fig-dividing-preshaping.tex
- book/figures/fig-dutch-oven-process.tex
- book/figures/fig-inverted-tray-method.tex
- book/figures/fig-kneading-process.tex
- book/figures/fig-liquid-starter-conversion.tex
- book/figures/fig-non-wheat-process.tex
- book/figures/fig-process-flat-bread.tex
- book/figures/fig-proofing-process.tex
- book/figures/fig-shaping-process.tex
- book/figures/fig-starter-maintenance.tex
- book/figures/fig-starter-process.tex
- book/figures/fig-starter-readiness.tex
- book/figures/fig-stiff-starter-conversion.tex
- book/figures/fig-wheat-sourdough-process.tex
- book/figures/fig-wheat-sourdough-starter-process.tex
- book/sourdough.sty
This will hopefully allow easier reading by identifying start and end point more easily
> Add color coding to flow charts

- book/figures/fig-kneading-process.tex
This fixes an issue in the bassinage flowchart as reported in #182
> Fix flowchart isuse

- book/colors.tex
- book/figures/export_figures.sh
- book/figures/fig-bulk-fermentation.tex
- book/figures/fig-dutch-oven-process.tex
- book/figures/fig-kneading-process.tex
- book/figures/fig-liquid-starter-conversion.tex
- book/figures/fig-starter-process.tex
- book/figures/fig-starter-readiness.tex
- book/figures/fig-stiff-starter-conversion.tex
- book/figures/flowcharts_tikz.tex
- book/figures/vars.tex
- book/makefile
- book/sourdough.sty
This adds a couple of small design changes to the flow charts.
> Change flowchart color

- book/cover/cover.tex
As it is manually placed, is prone to break on evry change of the page geometry...  This one looks good though in today's conditions.
> Fix front-page for one sided printing

- book/sourdough.sty
Few people will notice but this actually brings loads of improvements to line breaking, hanging punctuations etc.  Makes pdf even more beautiful!
> Enable micro-typographical improvements

- website/modify_build.rb
FYI @cedounet. Thanks again for the fix from PR #188
> Add flowcharts to menu

- book/book.tex
- book/intro/foreword.tex
- book/intro/preface.tex
Plus some very small changes in the text
> Restructure preface into logical paragraphs

- book/makefile
Some added infos I needed today
> Makefile updates

- book/book.tex
- book/sourdough.sty
This is less in your face than what we previously had.
Discussion in :
https://github.com/hendricius/the-sourdough-framework/discussions/201
There might be ways to make that better (not in your face and clickable ?)
https://tex.stackexchange.com/questions/555663/create-a-table-of-contents-with-links-in-all-text-and-different-colours-for-sect
> Change colors for links and hyperref

- book/basics/how-sourdough-works.tex
- book/book.tex
So it is coherent with the rest.
Also I can track which chapters I reviewed and which one I didn't that way :D.
> Add label for sourdough basics chapter

- book/bread-types/bread-types.tex
- book/tables/table-flat-bread-pancake-recipe.tex
This creates a short section with detailed instructions on how to make a flatbread.
> Improve flatbread recipe

- book/baking/baking.tex
- book/figures/fig-liquid-starter-conversion.tex
- book/figures/fig-stiff-starter-conversion.tex
- book/sourdough-starter/sourdough-starter-types.tex
- Now a flowchart (and a renamed label)
- More explicit wording as per https://github.com/hendricius/the-sourdough-framework/issues/234
> Correct wording, category for starter conversion

- book/tex4ebook.cfg
- website/modify_build.rb
Please Make sure it does not break website…
> Add list of flowcharts in ebook

- book/makefile
remove it from tools version.  We don't want to install that tool
> Remove azw3

- book/tables/table-flour-types.tex
> Right align numbers in flour-types table

- book/baking/baking.tex
> Fix mismatch between flowchart and figure

- book/book.tex
- book/storing-bread/storing-bread.tex
- book/tables/table-storing-bread-overview.tex
Usual fine tune of the chapter.
> Storage review

- Dockerfile
- book/book.tex
- book/storing-bread/storing-bread.tex
B&W ebooks broke it so merging it in emergency mode...
> Fix ci with Imagemagick

- book/book.tex
- book/glossary/glossary.tex
- book/sourdough.sty
Several fixes, micrographics, typography, LaTeX style and alphabetical order
> Fix glossary

- .gitignore
- book/glossary/glossary.tex
- book/troubleshooting/crumb-structures.tex
This adds retarding to the glossary and adds a note on how the times can be effected when starting with a warmer dough. This fixes #248
> Improve overfermentation when retarding a dough

- README.md
This adds the black and white version to the repo's README.
> Add black & white to README

- book/makefile
Now that parallel build is enabled
> Ensure dir is created before image BW conversion

- book/figures/fig-life-planet-sourdough-timeline.tex
- book/figures/flowcharts_tikz.tex
- book/history/sourdough-history.tex
- book/references.bib
After reading a really good book by Ed Young on microorganism I figured I update the history of sourdough bread a bit more.
> Add graphic showcasing evolution of life

- book/book.tex
> Move bibliography at the end of the book

- book/baking/baking.tex
- book/book.tex
- book/figures/fig-baking-process.tex
- book/figures/fig-dutch-oven-process.tex
- book/figures/flowcharts_tikz.tex
Flowcharts improvements and some text as well
> Review baking

- book/makefile
could give hints towards https://github.com/hendricius/the-sourdough-framework/issues/279
> Add dvisvgm version info

- Dockerfile
To deal with ebooks and tikz flowcharts
> Add dvsvgm to the docker image

- book/makefile
This reverts commit 2f3b8ec89b6bb63c6ad2439325fead00bd6ea8e3.
makes things worst...
> Revert "Fix giberrish website timeline"

- book/makefile
This reverts commit b559d727811a6621c6abeb484e01c602df578f06.
This should prevent the build from breaking eveb if it does not fix anything..
> Revert "Revert "Fix giberrish website timeline""

- book/tables/table-starter-usage-activity.tex
- book/wheat-sourdough/wheat-sourdough.tex
Mostly fonts, and array alignments.
> Wheat chapter small fixes

- book/history/sourdough-history.tex
Thanks @OzTK for the fixes. See #291
> Fix duplicate entry in history

- book/history/sourdough-history.tex
This improves the wording of the sentence. See #286
> Improve wording

- book/sourdough-starter/sourdough-starter-types.tex
@OzTK  remaining changes...  we made it complicated but finally there.  Sorry about that :smiley:
> Fix grammar

- .github/workflows/release-book-website.yml
- .github/workflows/test-book-website.yml
- website/modify_build.rb
This validates the format of the website and throws an error if something is fishy. See #302
> Validate website format

- makefile
- website/modify_build.rb
Adds missing links, re-order them.
> Fix list tables figures

- book/references.bib
- book/storing-bread/storing-bread.tex
Add a study I was linked pointing out to possible health benefits of freezing and cooking bread.
> Freezing bread could have benefits

- book/references.bib
Just a small cleanup to make sure all references are similarly formatted.
> Fix indentation/align on references

- website/modify_build.rb
> Fixes https links

- book/book-ebook.css
- book/makefile
For all floats actually...
@hendricius this is the first css I ever wrote, or even red LoL... could you please have a look.
> Force flowchart width to 100%

- book/bread-types/bread-types.tex
Moin Hendrik,
while reading through your amazing book, I stumbled over the tiniest of typos. Feel free to reject the PR and just fix it yourself. 😄 And keep up the great work!
Cheers,
Kevin
> Fix tiny typo in bread types.

- .github/workflows/test-book-website-pull-request.yml
- .github/workflows/test-book-website-push.yml
Uses latest image by default. For releasing the book and website a new image is built and stored as "latest".
> Change docker build process

- book/makefile
Also made clean target handle both
> Delete BW-book-epub directory in mrproper

- book/sourdough-starter/sourdough-starter-types.tex
This clarifies how much stiff starter to use
See #348
> Clarify stiff starter quantity

- book/baking/baking.tex
- book/basics/how-sourdough-works.tex
- book/bread-types/bread-types.tex
- book/flour-types/flour-types.tex
- book/history/sourdough-history.tex
- book/non-wheat-sourdough/non-wheat-sourdough.tex
- book/sourdough-starter/sourdough-starter-types.tex
- book/sourdough-starter/sourdough-starter.tex
- book/storing-bread/storing-bread.tex
- book/troubleshooting/misc.tex
- book/wheat-sourdough/wheat-sourdough.tex
This was a bad idea...:
https://tex.stackexchange.com/questions/2651/should-i-use-center-or-centering-for-figures-and-tables
floatrows not sure how it should work with flowcharts... so we use centring
I don't want to redefine all floats either as we use them for chapters title page.
> Remove centering for floats

- book/wheat-sourdough/wheat-sourdough.tex
> Add more pH Meter details

- .gitignore
> Remove duplicate from gitignore

- book/wheat-sourdough/wheat-sourdough.tex
Corrects relative scales of dough to starter when considering refreshing.
> Correct relative scales of dough and starter

- .github/workflows/release-book-website.yml
- .github/workflows/test-book-website.yml
- book/makefile
Should be cleaner on your local machine and faster on CI
> Ebook build dir

- .github/workflows/test-book-website.yml
We doing twice same things and that might be the reason for parallel build issues we still have.
> Some more ebook build dir

- .github/workflows/release-book-website.yml
- .github/workflows/test-book-website.yml
v3 was deprecated, switch to v4
> Use newer Github Actions version

- book/sourdough-starter/sourdough-starter.tex
This changes the text slightly to make it clearer what to best do with the discard that's piling up when making the starter initially.
> Fix discard instructions #409

- book/sourdough-starter/sourdough-starter.tex
This improves the figure's description.
> Fix #408 and improve chart description

- book/mix-ins/mix-ins.tex
- book/troubleshooting/misc.tex
This was written way before the mix-ins sections, made sense back then but not so much anymore so moving it out.
formatted text and added centering, labels etc while at it.
> Move mixing seed from troubleshooting to mix-ins

- book/figures/fig-starter-process.tex
- book/figures/flowcharts_tikz.tex
This is just to get our git repos in sync with all the commits in place in the right branch. No PR feedback has been addressed yet.
> Rebasing tiks_quick_debug to include earlier commit previously PR'ed to master.

- book/figures/fig-liquid-starter-conversion.tex
- book/figures/fig-stiff-starter-conversion.tex
This should fix the issues with the repeat arrows not being aligned very well. All the trial and error has been taken out of it, and it should respond to changes better.
> Layout "Repeat 3 Times" loops in better way.

- .github/workflows/test-book-website.yml
- book/figures/fig-liquid-starter-conversion.tex
- book/figures/fig-stiff-starter-conversion.tex
- book/makefile
- makefile
This just moves things around and simplify naming…
> Reorg makefile

- book/pgfsys-dvisvgm4ht.def
- book/tex4ebook.cfg
- book/website.cfg
Can you please review this works for you as well?
> Chemical equation fix

- book/basics/how-sourdough-works.tex
ajes from Discord pointed this out. Improvements by Cookiedust. Thanks!
> Improve text for enzymes

- website/modify_build.rb
I believe the link should point to the TLDR PDF (Correct me if I am wrong)
> Updates TLDR Link in Menu

- book/basics/how-sourdough-works.tex
- book/bread-types/bread-types.tex
- book/history/sourdough-history.tex
- book/mix-ins/mix-ins.tex
- book/non-wheat-sourdough/non-wheat-sourdough.tex
- book/sourdough-starter/sourdough-starter-types.tex
- book/sourdough-starter/sourdough-starter.tex
- book/troubleshooting/crumb-structures.tex
- book/troubleshooting/misc.tex
- book/wheat-sourdough/wheat-sourdough.tex
A few reformating as well, commit mainly about consistency
> Harmonize labels names and use centering

- book/history/sourdough-history.tex
Theuy defo were not in his book.
> Do not pretend Evan's mills were steam powered

- book/nameref.4ht
Chapters with Komascript need a special treatment.  See: https://github.com/michal-h21/make4ht/issues/166#issuecomment-2695488065
> Fix wrong text in html with nameref
